### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by DivXPro** [Davemane42/ComfyUI_Dave_CustomNode#10]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1450626/230326538-9dfe152a-34f5-48f8-8823-2d8acab26aaa.png">
I am using latest version of comfyui and this custom node. But I cant not add new input and display the postion preview on the node.
How to fix it ?

**Comment by lolman838** [comment]
If you are using Colab, check out my issue to find out why this is happening.
To fix this, execute following command:
!cp -r custom_nodes/ComfyUI_Dave_CustomNode/javascript web/extensions/Davemane42

**Comment by DivXPro** [comment]
I got it
