### ISSUE TITLE
No options on Node.

### ISSUE THREAD

**Issue by superskirv** [Davemane42/ComfyUI_Dave_CustomNode#2]
Not working, only 2 links on this node, one input, one output.

I am new to ComfyUI, so I may be doing this wrong. I have downloaded the portable windows build of ComfyUI and I have used mklink to point the models to the correct folders, so I have all my checkpoints/loras/embeddings/etc. I extracted and placed the custom node files(Both *.py and *.js) into the "custom_nodes" folder. The menu item shows up in Comfy UI under Add Node > Davemane42 > MultiAreaConditioning, however I only get 2 links. 1 input, named "conditioning0" and 1 output "CONDITIONING". When I right click input and output options are greyed out and properties does nothing.

Im guessing I need to place the files in a different location? I downloaded the v2.0 files from civitai.com, but I downloaded the v2.1 update from github when it wasnt working. no change with current configuration.

**Comment by superskirv** [comment]
Thank you.

**Comment by DivXPro** [comment]
how do u fix it ?
