### ISSUE TITLE
Only noise in the output

### ISSUE THREAD

**Issue by JoBilert** [Davemane42/ComfyUI_Dave_CustomNode#4]
I tried your custom multi-region node in a current version of comfyUI, but my outputs are only noise. When I mute the node and  and use one of the inputs directly it works all fine. 

Do you know any reason for this?

**Comment by Davemane42** [comment]
can you share your workflow, i remember having this when i was setting the nodes but dont remember what it was.
I know that its usually best to dedicate one of the layer to be "fullscreen" or the hole are gonna be noisy/brown
