### ISSUE TITLE
the lack of NODE_CLASS_MAPPINGS 

### ISSUE THREAD

**Issue by fractal-fumbler** [Davemane42/ComfyUI_Dave_CustomNode#5]
hello :)

comfyui @27fc64ad469c07d8f84b2c2791a593f1cf2c7b59

after switching to update got this error.
```python
python main.py --listen                    
A matching Triton is not available, some optimizations will not be enabled.                                             
Error caught was: No module named 'triton'                                                                              
Set vram state to: NORMAL VRAM 
Using xformers cross attention 
Skip /tmp/ComfyUI/custom_nodes/MultiAreaConditioning.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
Skip /tmp/ComfyUI/custom_nodes/MultiLatentComposite.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
```

**Comment by Davemane42** [comment]
did you also put the __init__.py in the folder?

for a correct instalation, the files need to be arranged like so.

ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   __init__.py
   MultiAreaConditioning.py
   MultiLatentComposite.py
   
ComfyUI\web\extensions\Davemane42
   MultiAreaConditioning.js
   MultiLatentComposite.js
   utils.js

**Comment by fractal-fumbler** [comment]
missed the `init.py` moment.

also missed the part of creating `ComfyUI_Dave_CustomNode` subfolder.

thanks a lot for help! now it's loading without errors :)
