### ISSUE TITLE
ComfyUI almost freezes after using MultiAreaConditioning

### ISSUE THREAD

**Issue by meor9zcu12** [Davemane42/ComfyUI_Dave_CustomNode#7]
To reproduce:
1. Start a empty workflow
2. Just add a MultiAreaConditioning
3. Add more conditionings
4. Click a lot and keep switching to different index, i.e. 0 to 5 and repeat 5 to 0
5. The UI starts to freeze, the bottom panel become empty, cannot drag UI.
6. Try to add a new node, but the new node added will only appear after window resizing, and still cannot be selectable.
7. Save still work, but workflow may still freeze after reload the save.

![image](https://user-images.githubusercontent.com/82598626/229576725-596e8864-04e7-4640-982c-47216316341b.png)

**Comment by Davemane42** [comment]
ill look into it

**Comment by Davemane42** [comment]
fixed the problem with [c63fe14](https://github.com/Davemane42/ComfyUI_Dave_CustomNode/commit/c63fe1467aa73494aef28454c4f16046a0c653a1), sometime index would output really small values like 1.0000000045 and mess thing up
