### ISSUE TITLE
Comfy UI window freezes when 'index' exceeds number of 'condition' interfaces

### ISSUE THREAD

**Issue by moonlightxp** [Davemane42/ComfyUI_Dave_CustomNode#8]
When I adjust the number of 'index' to be greater than the number of 'condition' interfaces, the Comfy UI window will be frozen and I cannot click on any node until I refresh the webpage.

Reproduction steps:
1. Open the Comfy UI interface.
2. Add a MultiAreaConditon Node.
3. Adjust the value of 'index' to be greater than the number of input interfaces in the 'condition' node.

The same issue also occurs with the MultiLetentComposite node.

**Comment by Davemane42** [comment]
You're mot the first to mention it, just got home.
ill take a look into it

**Comment by Davemane42** [comment]
cant really replicate index being greated then the number of conditions but i fixed another problem related to the index slider
[c63fe14](https://github.com/Davemane42/ComfyUI_Dave_CustomNode/commit/c63fe1467aa73494aef28454c4f16046a0c653a1), where it would output really small values like 1.0000000045 and mess thing up.

dont know if that would fix it for you
