### ISSUE TITLE
Creating folder in wrong directory on Colab

### ISSUE THREAD

**Issue by lolman838** [Davemane42/ComfyUI_Dave_CustomNode#9]
In Colab instead of creating a folder "Daveman42" in web\extensions\, it makes folder "web\extensions\Davemane42" in ComfyUI folder
![image](https://user-images.githubusercontent.com/124892725/230137829-c3d82dc0-99bd-4e63-bc5a-5f00b2f89134.png)

**Comment by Davemane42** [comment]
fixed with #12
